function [tree] = sci_ZOH1(tree)
// Generated by M2SCI
// Conversion function for Matlab ZOH1
// Input: tree = Matlab funcall tree
// Ouput: tree = Scilab equivalent for tree

tree=Funcall("exec",1,Rhs(tree.name),tree.lhs)
endfunction
